"""
Interpretable per-candidate feature vectors for learned T landmark ranking.

Candidates are generated by PyHEARTS; the ranker only scores pre-generated landmarks.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from pyhearts.processing.t_landmark_ensemble import TLandmarkEnsembleScore, _primary_source
from pyhearts.processing.t_morphology_routing import normalize_t_morphology_tag

NUMERIC_FEATURES: Tuple[str, ...] = (
    "timing_prior_score",
    "template_prior_score",
    "morphology_score",
    "derivative_support",
    "prominence_score",
    "beat_corr_support",
    "local_shape_score",
    "neighborhood_consistency",
    "candidate_stability",
    "local_confidence",
    "candidate_count",
    "score_margin_to_next",
)

CANDIDATE_TYPE_COLUMNS: Tuple[str, ...] = (
    "candidate_type_positive_peak",
    "candidate_type_negative_peak",
    "candidate_type_derivative_zero_crossing",
    "candidate_type_template_projected_apex",
    "candidate_type_rising_edge_onset",
    "candidate_type_max_curvature",
    "candidate_type_amplitude_plateau_midpoint",
    "candidate_type_refined_apex",
    "candidate_type_refined_dzc",
)

MORPHOLOGY_COLUMNS: Tuple[str, ...] = (
    "morphology_normal",
    "morphology_biphasic",
    "morphology_inverted",
    "morphology_plateau",
    "morphology_rising_edge",
)

FEATURE_COLUMNS: Tuple[str, ...] = NUMERIC_FEATURES + CANDIDATE_TYPE_COLUMNS + MORPHOLOGY_COLUMNS

_CANDIDATE_TYPE_MAP = {
    "positive_peak": "candidate_type_positive_peak",
    "negative_peak": "candidate_type_negative_peak",
    "derivative_zero_crossing": "candidate_type_derivative_zero_crossing",
    "template_projected_apex": "candidate_type_template_projected_apex",
    "rising_edge_onset": "candidate_type_rising_edge_onset",
    "max_curvature": "candidate_type_max_curvature",
    "amplitude_plateau_midpoint": "candidate_type_amplitude_plateau_midpoint",
    "refined_apex": "candidate_type_refined_apex",
    "refined_dzc": "candidate_type_refined_dzc",
}

_MORPHOLOGY_MAP = {
    "normal": "morphology_normal",
    "biphasic_positive_negative": "morphology_biphasic",
    "inverted_t": "morphology_inverted",
    "plateau": "morphology_plateau",
    "rising_edge": "morphology_rising_edge",
}


def morphology_class_tag(morphology: str) -> str:
    return normalize_t_morphology_tag(morphology)


def score_margin_to_next(scored: Sequence[TLandmarkEnsembleScore], sample_idx: int) -> float:
    """Ensemble total margin vs next-best candidate on the same beat."""
    if not scored:
        return float("nan")
    totals = sorted((float(s.total) for s in scored), reverse=True)
    if len(totals) < 2:
        return float("nan")
    mine = next((float(s.total) for s in scored if int(s.sample_idx) == int(sample_idx)), float("nan"))
    if not np.isfinite(mine):
        return float("nan")
    second = totals[1] if totals[0] == mine else totals[0]
    return mine - second


def build_candidate_feature_row(
    *,
    score: TLandmarkEnsembleScore,
    candidate_type: str,
    morphology_class: str,
    candidate_count: int,
    scored_on_beat: Sequence[TLandmarkEnsembleScore],
) -> Dict[str, float]:
    """Numeric + one-hot features for one candidate (no record ID)."""
    row: Dict[str, float] = {
        "timing_prior_score": float(score.timing_prior_score),
        "template_prior_score": float(score.template_prior_score),
        "morphology_score": float(score.morphology_score),
        "derivative_support": float(score.derivative_support),
        "prominence_score": float(score.prominence_score),
        "beat_corr_support": float(score.beat_corr_support),
        "local_confidence": float(score.local_confidence),
        "candidate_count": float(candidate_count),
        "score_margin_to_next": score_margin_to_next(scored_on_beat, score.sample_idx),
    }
    ev = score.evidence
    if ev is not None:
        row["local_shape_score"] = float(ev.local_shape_score)
        row["neighborhood_consistency"] = float(ev.neighborhood_consistency)
        row["candidate_stability"] = float(ev.candidate_stability)
    else:
        row["local_shape_score"] = float("nan")
        row["neighborhood_consistency"] = float("nan")
        row["candidate_stability"] = float("nan")

    primary = _primary_source(candidate_type)
    for col in CANDIDATE_TYPE_COLUMNS:
        row[col] = 0.0
    ctype_col = _CANDIDATE_TYPE_MAP.get(primary)
    if ctype_col:
        row[ctype_col] = 1.0

    morph = morphology_class_tag(morphology_class)
    for col in MORPHOLOGY_COLUMNS:
        row[col] = 0.0
    mcol = _MORPHOLOGY_MAP.get(morph)
    if mcol:
        row[mcol] = 1.0

    return row


def rows_to_matrix(rows: Sequence[Dict[str, float]]) -> Tuple[np.ndarray, List[str]]:
    """Stack feature dicts; NaN → column median (train) or 0 (handled at train time)."""
    X = np.array([[float(r.get(c, np.nan)) for c in FEATURE_COLUMNS] for r in rows], dtype=float)
    return X, list(FEATURE_COLUMNS)


def impute_median(X: np.ndarray, medians: Optional[np.ndarray] = None) -> Tuple[np.ndarray, np.ndarray]:
    if medians is None:
        medians = np.nanmedian(X, axis=0)
        medians = np.where(np.isfinite(medians), medians, 0.0)
    out = X.copy()
    for j in range(out.shape[1]):
        bad = ~np.isfinite(out[:, j])
        if np.any(bad):
            out[bad, j] = medians[j]
    return out, medians
